apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-volume
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Chart.Name }}-claim
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data"