apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: {{ .Chart.Name }}-volume
  resources:
    requests:
      storage: 1Mi