apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-set
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: {{ .Chart.Name }}-service
  replicas: {{ .Values.replicas}}
  template:
    metadata:
      name: set-member
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: {{ printf "\"%s-%s\"" .Chart.Name .Values.templateName }}
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: {{ .Chart.Name }}-claim-template
      spec:
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        volumeName: {{ .Chart.Name }}-volume
        resources:
          requests:
            storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80