apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-volume
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"